Transform: AWS::Server-less-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      CodeUri: s3://deploy-macro/c48f3d5adff5ffbdacc3d24e577971c5
      Handler: index.handler
  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: MyMacro
      FunctionName:
        Fn::GetAtt:
        - Function
        - Arn
