AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Ec2ImageId:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
  InstanceType:
    Description: "EC2 instance type"
    Type: "String"
    Default: "t2.micro"
  KeyName:
    Description: "Name of existing EC2 KeyPairs to enable SSH access to the instance"
    Type: "AWS::EC2::KeyPair::KeyName"
Resources:
  WebServerInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref "Ec2ImageId"
      InstanceType: !Ref "InstanceType"
      KeyName: !Ref "KeyName"